name: flutter_fixtures_dio
description: "Dio implementation for Flutter Fixtures"
version: 0.1.1
homepage: https://github.com/brotoo25/flutter_fixtures
repository: https://github.com/brotoo25/flutter_fixtures
issue_tracker: https://github.com/brotoo25/flutter_fixtures/issues
documentation: https://github.com/brotoo25/flutter_fixtures#readme

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_fixtures_core: ^0.1.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9

topics:
  - mock
  - http
  - testing
  - fixtures
